// <auto-generated />
using Logstore.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Logstore.Infra.Migrations
{
    [DbContext(typeof(LogstoreDbContext))]
    [Migration("20201014181201_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("LogstoreAPI")
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("Logstore.Domain.Entities.PizzaSabores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativa");

                    b.Property<bool>("Disponivel");

                    b.Property<string>("NomeSabor")
                        .IsRequired();

                    b.Property<decimal>("PrecoUnitario");

                    b.HasKey("Id");

                    b.ToTable("PizzaSabores");
                });
#pragma warning restore 612, 618
        }
    }
}
